# Type stub for peclet.core.geom — GENERATED by `python -m nanobind.stubgen -m peclet.core.geom -o packaging/core_geom.pyi`
# (PYTHONPATH at the python build tree). Do not hand-edit; regenerate after changing geom_bindings.cpp.
"""
Analytic-SDF scene authoring: SceneBuilder (leaves + CSG + transforms + instancing), batch evaluation, lattice baking, and rigid-body mass properties (mass, COM, inertia tensor, principal moments + quaternion) by implicit quadrature.
"""

from collections.abc import Sequence
from typing import Annotated

import numpy
from numpy.typing import NDArray


class SceneBuilder:
    def __init__(self) -> None: ...

    def add_leaf(self, kind: str, params: Sequence[float], translation: Sequence[float] = [0.0, 0.0, 0.0], rotation: Sequence[float] = [0.0, 0.0, 0.0, 1.0], scale: float = 1.0) -> int:
        """
        Add a leaf primitive; returns its node index. kind: sphere [r], box [hx,hy,hz], hollow_cylinder [rOuter,height,thickness] (y axis, distance-exact), hollow_cylinder_shell [rOuter,rInner,height] (z axis, sign-exact), capsule [r,halfLength] (y), torus [R,r] (y), cone [rBottom,rTop,halfHeight] (y), ellipsoid [rx,ry,rz] (BOUND), superquadric [rx,ry,rz,e] (BOUND). rotation is a quaternion (x, y, z, w).
        """

    def add_union(self, a: int, b: int, translation: Sequence[float] = [0.0, 0.0, 0.0], rotation: Sequence[float] = [0.0, 0.0, 0.0, 1.0], scale: float = 1.0) -> int: ...

    def add_intersection(self, a: int, b: int, translation: Sequence[float] = [0.0, 0.0, 0.0], rotation: Sequence[float] = [0.0, 0.0, 0.0, 1.0], scale: float = 1.0) -> int: ...

    def add_difference(self, a: int, b: int, translation: Sequence[float] = [0.0, 0.0, 0.0], rotation: Sequence[float] = [0.0, 0.0, 0.0, 1.0], scale: float = 1.0) -> int:
        """a minus b."""

    def add_reframed(self, root: int, translation: Sequence[float] = [0.0, 0.0, 0.0], rotation: Sequence[float] = [0.0, 0.0, 0.0, 1.0], scale: float = 1.0) -> int:
        """
        Deep-copy the subtree and pre-compose this transform onto the copied root, so eval_new(p) = eval_old(toLocal(W, p)) -- i.e. this PLACES the copy at W. With the inverse principal transform from body_properties (rotation = conjugate of its quat, translation = -com rotated by the conjugate... see principal_frame()), the copy's canonical frame IS the principal body frame, exactly, with no resampling.
        """

    def principal_frame(self, root: int, lo: Sequence[float], hi: Sequence[float], n: int = 32, order: int = 5, nseg: int = 8) -> int:
        """
        Measure the subtree's mass properties and return a NEW root whose canonical frame is the principal body frame (COM at the origin, axes principal) -- the one-call answer to 'my shape's reference frame is not its principal frame'. The original subtree is untouched.
        """

    def add_instance(self, root: int, translation: Sequence[float] = [0.0, 0.0, 0.0], rotation: Sequence[float] = [0.0, 0.0, 0.0, 1.0], scale: float = 1.0, lin_vel: Sequence[float] = [0.0, 0.0, 0.0], ang_vel: Sequence[float] = [0.0, 0.0, 0.0], center: Sequence[float] = [float('nan'), float('nan'), float('nan')], material: int = -1) -> int:
        """
        Place a tree in the world; returns the instance index. What flow's set_scene and the resolved coupling consume. `center` is the centre of rotation for ang_vel: leave it NaN (the default) and it FOLLOWS the body (the translation, re-anchored on every set_instance_transform); give any finite point and it is PINNED there in world coordinates -- (0, 0, 0) included. (Raw instance arrays keep the legacy reading of an all-zero centre as 'follows the body'; pin a world-origin centre from a raw array through flow's set_instance_motion(center=...).)
        """

    def encode(self) -> tuple:
        """
        The flat (node_ints, node_reals, inst_ints, inst_reals) arrays -- exactly what flow.set_scene, dem.add_analytic_wall and dem.add_scene_shape take.
        """

    def eval(self, points: Annotated[NDArray[numpy.float64], dict(shape=(None, 3), order='C')]) -> NDArray[numpy.float64]:
        """
        Signed distance of the whole scene (min over instances) at (N,3) world points. Authoring/debug; solvers evaluate on device.
        """

    def eval_root(self, root: int, points: Annotated[NDArray[numpy.float64], dict(shape=(None, 3), order='C')]) -> NDArray[numpy.float64]:
        """
        Signed distance of ONE subtree, in its own canonical frame, at (N,3) points.
        """

    def eval_root_grad(self, root: int, points: Annotated[NDArray[numpy.float64], dict(shape=(None, 3), order='C')]) -> tuple:
        """
        Value AND analytic gradient of one subtree at (N,3) canonical points, one traversal: (values (N,), gradients (N,3), unnormalised). At CSG ridges the gradient is the ACTIVE branch's exact normal (deterministic left tie-break), not a finite-difference smear.
        """

    def bake(self, root: int, origin: Sequence[float], spacing: Sequence[float], dims: Sequence[int]) -> NDArray[numpy.float32]:
        """
        Sample a subtree on a lattice: flat float32, x-fastest (idx = i + j*nx + k*nx*ny), at nodes origin + (i,j,k)*spacing -- the layout dem's grid-SDF particles and shell generation consume.
        """

    def body_properties(self, root: int, lo: Sequence[float], hi: Sequence[float], n: int = 32, order: int = 5, nseg: int = 8, density: float = 1.0) -> dict:
        """
        Mass properties of {subtree < 0} over [lo, hi] (which MUST contain the solid), constant density, by implicit quadrature: dict with volume, mass, com, inertia_tensor (3,3 about the COM), principal (3, ascending), rotation (3,3; columns = principal axes, p_input = com + R p_body) and quat (x,y,z,w). Sign-exact bracketing means bound-only leaves (ellipsoid, superquadric, CSG) carry NO systematic bias; measured ~4e-6 relative at n=32 (ctest geom_body).
        """

    def num_nodes(self) -> int: ...

    def num_instances(self) -> int: ...
